chore: build script updates
uuidjs/uuid pull request #782
Opened 2024-07-21 14:14 UTC by broofa

* Add node@22 to test matrix
* Fix `runmd` build
* Change test:pack build dir to /tmp so it doesn't pollute source dir, and is not in-scope of project's package.json

2024-07-21 14:34 UTC, ctavan requested changes

2024-07-21 14:34 UTC, ctavan commented on scripts/testpack.sh
> +TEST_DIR=/tmp/test-pack
Prefer mktemp + trap: https://unix.stackexchange.com/a/509189

2024-07-21 18:48 UTC, broofa commented on scripts/testpack.sh
> +TEST_DIR=/tmp/test-pack
Done.

2024-07-21 21:37 UTC, ctavan commented on scripts/testpack.sh
> +TEST_DIR=$(mktemp -d)
Set up the trap right after this line so it takes effect if the script exits somewhere in the middle

2024-07-24 17:08 UTC, broofa commented
@ctavan Okay to merge?

2024-07-24 18:21 UTC, ctavan approved these changes

2024-07-24 18:21 UTC, ctavan commented on scripts/testpack.sh
> +trap 'popd && rm -rf $TEST_DIR' EXIT
I’d remove the popd from here… npm pack could fail and then you’d popd without having pushd’ed…

What we mostly care about with the trap is to no leave temp files.

If you want to overengineer, add a separate trap with just popd right after the pushd.

2024-07-24 20:07 UTC, merged