fix: apply stricter typing to the v4 signature
uuidjs/uuid pull request #831
Opened 2024-11-01 15:51 UTC by robbtraister

The `v4` function is guaranteed to return a string unless both the `options` and `buf` arguments are provided. By modifying the signature to denote these parameters as required for the `Uint8Array` case, we get the benefit of a stricter return type of `string` when simply calling `v4()`.

2024-11-01 18:23 UTC, broofa requested changes
Nice!  Thanks for the contribution.

Can you do me a favor and make update the other methods that take an optional `buf` argument as well? (v1.ts, v3.ts, v5.ts, and v7.ts)

2024-11-04 17:21 UTC, broofa commented
@robbtraister Thanks for the update.  This looks good.

FYI, I added [this commit](https://github.com/uuidjs/uuid/pull/831/commits/2e09800e3000d01789ddfd688d0c21578b4b2ad7) after realizing the overload types for v3 and v5 aren't really necessary.  (Right?  If I got that wrong, please let me know.)

2024-11-04 17:21 UTC, broofa approved these changes

2024-11-04 17:23 UTC, merged

2024-11-04 17:40 UTC, robbtraister commented
> @robbtraister Thanks for the update. This looks good.
> 
> FYI, I added [this commit](https://github.com/uuidjs/uuid/pull/831/commits/2e09800e3000d01789ddfd688d0c21578b4b2ad7) after realizing the overload types for v3 and v5 aren't really necessary. (Right? If I got that wrong, please let me know.)

Calling `v3("value", "namespace")` should always return `string`, but removing the overloads types it as `string | Uint8Array`.

Having said that, I only ever use `v4`, so 🤷

2024-11-04 17:59 UTC, broofa commented
> Calling v3("value", "namespace") should always return string, but removing the overloads types it as string | Uint8Array.

Ah, right... thanks for catching that!