docs: fix typo
uuidjs/uuid pull request #841
Opened 2024-11-25 17:56 UTC by felixrabe

2024-11-25 20:51 UTC, broofa requested changes
This change needs to be made in [README_js.md](https://github.com/uuidjs/uuid/blob/main/README_js.md), then run `npm run docs` to generate the README.md file.

2024-12-10 15:31 UTC, 818Nawaf approved these changes

2024-12-10 16:02 UTC, 818Nawaf approved these changes

2024-12-10 16:48 UTC, youneshenniwrites approved these changes

2025-01-05 13:12 UTC, broofa commented
No response from OP.

2025-01-05 13:12 UTC, closed without merging